<select name="lokacija" id="lokacija">
                            <option value="Banovići">Banovići</option>
                            <option value="Banja Luka">Banja Luka</option>
                            <option value="Berkovići">Berkovići</option>
                            <option value="Bileća">Bileća</option>
                            <option value="Bijeljina">Bijeljina</option>
                            <option value="Bosanska Dubica">Bosanska Dubica</option>
                            <option value="Bosanska Gradiška">Bosanska Gradiška</option>
                            <option value="Bosansko Grahovo">Bosansko Grahovo</option>
                            <option value="Bosanska Krupa">Bosanska Krupa</option>
                            <option value="Bosanska Kostajnica">Bosanska Kostajnica</option>
                            <option value="Bosanski Brod">Bosanski Brod</option>
                            <option value="Bosanski Novi">Bosanski Novi</option>
                            <option value="Bosanski Petrovac">Bosanski Petrovac</option>
                            <option value="Bosanski Šamac">Bosanski Šamac</option>
                            <option value="Bratunac">Bratunac</option>
                            <option value="Brčko">Brčko</option>
                            <option value="Breza">Breza</option>
                            <option value="Bugojno">Bugojno</option>
                            <option value="Busovača">Busovača</option>
                            <option value="Bužim">Bužim</option>
                            <option value="Cazin">Cazin</option>
                            <option value="Čajniče">Čajniče</option>
                            <option value="Čapljina">Čapljina</option>
                            <option value="Čelić">Čelić</option>
                            <option value="Čitluk">Čitluk</option>
                            <option value="Čelinac">Čelinac</option>
                            <option value="Doboj">Doboj</option>
                            <option value="Dobretići">Dobretići</option>
                            <option value="Domaljevac">Domaljevac</option>
                            <option value="Donji Vakuf">Donji Vakuf</option>
                            <option value="Drvar">Drvar</option>
                            <option value="Derventa">Derventa</option>
                            <option value="Foča">Foča</option>
                            <option value="Fojnica">Fojnica</option>
                            <option value="Gacko">Gacko</option>
                            <option value="Glamoč">Glamoč</option>
                            <option value="Gračanica">Gračanica</option>
                            <option value="Gradačac">Gradačac</option>
                            <option value="Grude">Grude</option>
                            <option value="Goražde">Goražde</option>
                            <option value="Gornji Vakuf">Gornji Vakuf</option>
                            <option value="Jablanica">Jablanica</option>
                            <option value="Jajce">Jajce</option>
                            <option value="Kakanj">Kakanj</option>
                            <option value="Kalesija">Kalesija</option>
                            <option value="Kalinovik">Kalinovik</option>
                            <option value="Kiseljak">Kiseljak</option>
                            <option value="Kladanj">Kladanj</option>
                            <option value="Ključ">Ključ</option>
                            <option value="Konjic">Konjic</option>
                            <option value="Kotor-Varoš">Kotor-Varoš</option>
                            <option value="Kreševo">Kreševo</option>
                            <option value="Kupres">Kupres</option>
                            <option value="Laktaši">Laktaši</option>
                            <option value="Livno">Livno</option>
                            <option value="Lukavac">Lukavac</option>
                            <option value="Lopare">Lopare</option>
                            <option value="Ljubinje">Ljubinje</option>
                            <option value="Ljubuški">Ljubuški</option>
                            <option value="Maglaj">Maglaj</option>
                            <option value="Milići">Milići</option>
                            <option value="Modriča">Modriča</option>
                            <option value="Mostar">Mostar</option>
                            <option value="Mrkonjić Grad">Mrkonjić Grad</option>
                            <option value="Neum">Neum</option>
                            <option value="Nevesinje">Nevesinje</option>
                            <option value="Novi Travnik">Novi Travnik</option>
                            <option value="Odžak">Odžak</option>
                            <option value="Olovo">Olovo</option>
                            <option value="Orašje">Orašje</option>
                            <option value="Pale">Pale</option>
                            <option value="Posušje">Posušje</option>
                            <option value="Prozor">Prozor</option>
                            <option value="Pale-Prača">Pale-Prača</option>
                            <option value="Prijedor">Prijedor</option>
                            <option value="Prnjavor">Prnjavor</option>
                            <option value="Ravno">Ravno</option>
                            <option value="Rogatica">Rogatica</option>
                            <option value="Rudo">Rudo</option>
                            <option value="Sanski Most">Sanski Most</option>
                            <option value="Sapna">Sapna</option>
                            <option value="Sarajevo">Sarajevo</option>
                            <option value="Skender Vakuf">Skender Vakuf</option>
                            <option value="Sokolac">Sokolac</option>
                            <option value="Srbac">Srbac</option>
                            <option value="Srebrenica">Srebrenica</option>
                            <option value="Srebrenik">Srebrenik</option>
                            <option value="Stanari">Stanari</option>
                            <option value="Stolac">Stolac</option>
                            <option value="Šipovo">Šipovo</option>
                            <option value="Široki Brijeg">Široki Brijeg</option>
                            <option value="Teočak">Teočak</option>
                            <option value="Teslić">Teslić</option>
                            <option value="Tešanj">Tešanj</option>
                            <option value="Tomislavgrad">Tomislavgrad</option>
                            <option value="Travnik">Travnik</option>
                            <option value="Trebinje">Trebinje</option>
                            <option value="Tuzla">Tuzla</option>
                            <option value="Usora">Usora</option>
                            <option value="Ustiprača">Ustiprača</option>
                            <option value="Vareš">Vareš</option>
                            <option value="Velika Kladuša">Velika Kladuša</option>
                            <option value="Visoko">Visoko</option>
                            <option value="Višegrad">Višegrad</option>
                            <option value="Vitez">Vitez</option>
                            <option value="Vogošća">Vogošća</option>
                            <option value="Zavidovići">Zavidovići</option>
                            <option value="Zenica">Zenica</option>
                            <option value="Zvornik">Zvornik</option>
                            <option value="Žepče">Žepče</option>
                            <option value="Živinice">Živinice</option>

                            <!-- HRVATSKA -->


                            <option value="Bakar">Bakar</option>
                            <option value="Beli Manastir">Beli Manastir</option>
                            <option value="Belišće">Belišće</option>
                            <option value="Benkovac">Benkovac</option>
                            <option value="Biograd na Moru">Biograd na Moru</option>
                            <option value="Bjelovar">Bjelovar</option>
                            <option value="Buje">Buje</option>
                            <option value="Buzet">Buzet</option>
                            <option value="Cres">Cres</option>
                            <option value="Crikvenica">Crikvenica</option>
                            <option value="Čabar">Čabar</option>
                            <option value="Čakovec">Čakovec</option>
                            <option value="Čazma">Čazma</option>
                            <option value="Daruvar">Daruvar</option>
                            <option value="Delnice">Delnice</option>
                            <option value="Donja Stubica">Donja Stubica</option>
                            <option value="Donji Miholjac">Donji Miholjac</option>
                            <option value="Drniš">Drniš</option>
                            <option value="Dubrovnik">Dubrovnik</option>
                            <option value="Duga Resa">Duga Resa</option>
                            <option value="Dugo Selo">Dugo Selo</option>
                            <option value="Đakovo">Đakovo</option>
                            <option value="Đurđevac">Đurđevac</option>
                            <option value="Garešnica">Garešnica</option>
                            <option value="Glina">Glina</option>
                            <option value="Gospić">Gospić</option>
                            <option value="Grubišno Polje">Grubišno Polje</option>
                            <option value="Hrvatska Kostajnica">Hrvatska Kostajnica</option>
                            <option value="Hvar">Hvar</option>
                            <option value="Ilok">Ilok</option>
                            <option value="Imotski">Imotski</option>
                            <option value="Ivanec">Ivanec</option>
                            <option value="Ivanić-Grad">Ivanić-Grad</option>
                            <option value="Jastrebarsko">Jastrebarsko</option>
                            <option value="Karlovac">Karlovac</option>
                            <option value="Kastav">Kastav</option>
                            <option value="Kaštela">Kaštela</option>
                            <option value="Klanjec">Klanjec</option>
                            <option value="Knin">Knin</option>
                            <option value="Komiža">Komiža</option>
                            <option value="Koprivnica">Koprivnica</option>
                            <option value="Korčula">Korčula</option>
                            <option value="Kraljevica">Kraljevica</option>
                            <option value="Krapina">Krapina</option>
                            <option value="Križevci">Križevci</option>
                            <option value="Krk">Krk</option>
                            <option value="Kutina">Kutina</option>
                            <option value="Kutjevo">Kutjevo</option>
                            <option value="Labin">Labin</option>
                            <option value="Lepoglava">Lepoglava</option>
                            <option value="Lipik">Lipik</option>
                            <option value="Ludbreg">Ludbreg</option>
                            <option value="Makarska">Makarska</option>
                            <option value="Mali Lošinj">Mali Lošinj</option>
                            <option value="Metković">Metković</option>
                            <option value="Mursko Središće">Mursko Središće</option>
                            <option value="Našice">Našice</option>
                            <option value="Nin">Nin</option>
                            <option value="Nova Gradiška">Nova Gradiška</option>
                            <option value="Novalja">Novalja</option>
                            <option value="Novi Marof">Novi Marof</option>
                            <option value="Novi Vinodolski">Novi Vinodolski</option>
                            <option value="Novigrad">Novigrad</option>
                            <option value="Novska">Novska</option>
                            <option value="Obrovac">Obrovac</option>
                            <option value="Ogulin">Ogulin</option>
                            <option value="Omiš">Omiš</option>
                            <option value="Opatija">Opatija</option>
                            <option value="Opuzen">Opuzen</option>
                            <option value="Orahovica">Orahovica</option>
                            <option value="Oroslavje">Oroslavje</option>
                            <option value="Osijek">Osijek</option>
                            <option value="Otočac">Otočac</option>
                            <option value="Otok">Otok</option>
                            <option value="Ozalj">Ozalj</option>
                            <option value="Pag">Pag</option>
                            <option value="Pakrac">Pakrac</option>
                            <option value="Pazin">Pazin</option>
                            <option value="Petrinja">Petrinja</option>
                            <option value="Pleternica">Pleternica</option>
                            <option value="Ploče">Ploče</option>
                            <option value="Popovača">Popovača</option>
                            <option value="Poreč">Poreč</option>
                            <option value="Požega">Požega</option>
                            <option value="Pregrada">Pregrada</option>
                            <option value="Prelog">Prelog</option>
                            <option value="Pula">Pula</option>
                            <option value="Rijeka">Rijeka</option>
                            <option value="Rovinj">Rovinj</option>
                            <option value="Samobor">Samobor</option>
                            <option value="Senj">Senj</option>
                            <option value="Sinj">Sinj</option>
                            <option value="Sisak">Sisak</option>
                            <option value="Skradin">Skradin</option>
                            <option value="Slatina">Slatina</option>
                            <option value="Slavonski Brod">Slavonski Brod</option>
                            <option value="Slunj">Slunj</option>
                            <option value="Solin">Solin</option>
                            <option value="Split">Split</option>
                            <option value="Stari Grad">Stari Grad</option>
                            <option value="Supetar">Supetar</option>
                            <option value="Sveta Nedelja">Sveta Nedelja</option>
                            <option value="Sveti Ivan Zelina">Sveti Ivan Zelina</option>
                            <option value="Šibenik">Šibenik</option>
                            <option value="Trilj">Trilj</option>
                            <option value="Trogir">Trogir</option>
                            <option value="Umag">Umag</option>
                            <option value="Valpovo">Valpovo</option>
                            <option value="Varaždin">Varaždin</option>
                            <option value="Varaždinske Toplice">Varaždinske Toplice</option>
                            <option value="Velika Gorica">Velika Gorica</option>
                            <option value="Vinkovci">Vinkovci</option>
                            <option value="Virovitica">Virovitica</option>
                            <option value="Vis">Vis</option>
                            <option value="Vodice">Vodice</option>
                            <option value="Vodnjan">Vodnjan</option>
                            <option value="Vrbovec">Vrbovec</option>
                            <option value="Vrbovsko">Vrbovsko</option>
                            <option value="Vrgorac">Vrgorac</option>
                            <option value="Vrlika">Vrlika</option>
                            <option value="Vukovar">Vukovar</option>
                            <option value="Zabok">Zabok</option>
                            <option value="Zadar">Zadar</option>
                            <option value="Zagreb">Zagreb</option>
                            <option value="Zaprešić">Zaprešić</option>
                            <option value="Zlatar">Zlatar</option>
                            <option value="Županja">Županja</option>
                        </select>